services:
  quagmire-bot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - bot-data:/data  # Persistent volume for database storage
    command: npm run watch:start

volumes:
  bot-data:  # Named volume for persistent data storage